### PR TITLE
Fix missing attach to deployment option for obc

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Resolves: bz#2089786

Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@bipuladh , @SanjalKatiyar , @GowthamShanmugam Please review

**Comment by TimothyAsirJeyasing** [comment]
image

**Review by bipuladh — CHANGES_REQUESTED** [review]
https://github.com/red-hat-storage/odf-console/blob/master/packages/odf/components/mcg/ObjectBucketClaim.tsx#L398-L401
Make similar changes at ^. You have not fixed it for details page yet.

**Pull request merged**
