### PR TITLE
Move i18n-scripts under scripts

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Signed-off-by: Timothy Asir <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@bipuladh , @SanjalKatiyar Please review

**Comment by TimothyAsirJeyasing** [comment]
@SanjalKatiyar Tested and Updated the path, Please review

**Comment by SanjalKatiyar** [comment]
/hold
rebase the PR on latest master

**Comment by bipuladh** [comment]
https://github.com/red-hat-storage/odf-console/issues/551

**Pull request merged**
