### PR TITLE
Remove date from x-axis label of ceph RBD snapshot graph

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
Screenshot from 2023-07-28 14-26-32

**Comment by TimothyAsirJeyasing** [comment]
/retitle Bug 2223692: Remove date from x-axis label of ceph RBD snapshot graph

**Review by GowthamShanmugam — APPROVED** [review]

**Review by GowthamShanmugam — COMMENTED** [review]
Increase shared package version on package.json and yarn.lock

**Review by GowthamShanmugam — CHANGES_REQUESTED** [review]
Increase shared package version on package.json and yarn.lock

**Review by GowthamShanmugam — APPROVED** [review]

**Comment by TimothyAsirJeyasing** [comment]
Rebased with latest master

**Comment by SanjalKatiyar** [comment]
fix build test...

**Comment by TimothyAsirJeyasing** [comment]
Rebased with current master

**Review by GowthamShanmugam — APPROVED** [review]

**Comment by GowthamShanmugam** [comment]
/retitle Remove date from x-axis label of ceph RBD snapshot graph

**Comment by SanjalKatiyar** [comment]
for some reason e2e tests are failing again and again for this particular PR @TimothyAsirJeyasing PTAL if something needs fixing or not...

**Pull request merged**
