### PR TITLE
Update copyright license details

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Signed-off-by: Timothy Asir <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@SanjalKatiyar Please review

**Comment by TimothyAsirJeyasing** [comment]
Copyright license details updated as per the discussion with legal team and the document
https://source.redhat.com/departments/legal/redhatintellectualproperty/intellectual_property_and_ip_litigation_wiki/copyright_notices_in_source_code

**Comment by TimothyAsirJeyasing** [comment]
@SanjalKatiyar Please review

**Review by bipuladh — APPROVED** [review]
/lgtm

**Pull request merged**
