### PR TITLE
Attach OBC to Deployment - fix incorrect validations

### PR DESCRIPTION
**Pull request by SanjalKatiyar**
https://bugzilla.redhat.com/show_bug.cgi?id=2302575

Screenshot 2024-08-20 at 4 43 33 PM
Screenshot 2024-08-20 at 4 43 39 PM
Screenshot 2024-08-20 at 4 43 59 PM
Screenshot 2024-08-20 at 4 44 16 PM
Screenshot 2024-08-20 at 4 44 42 PM

### CODE REVIEW

**Review by GowthamShanmugam — COMMENTED** [review]
LGTM

**Comment by SanjalKatiyar** [comment]
@GowthamShanmugam @bipuladh can we tag it, if it looks good ??

**Review by GowthamShanmugam — APPROVED** [review]

**Pull request merged**
