### PR TITLE
Bug DFBUGS-936: [release-4.15-compatibility] css-tools: Improper Input Validation causes Denial of Service via Regular Expression

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Issue: https://issues.redhat.com/browse/DFBUGS-936

### CODE REVIEW

**Review by alfonsomthd — APPROVED** [review]

**Comment by GowthamShanmugam** [comment]
/retitle Bug DFBUGS-936: [release-4.15-compatibility] css-tools: Improper Input Validation causes Denial of Service via Regular Expression

**Pull request merged**
