### PR TITLE
change schema type for pvc-name from string to type PersistenVolumeClaimKind

### PR DESCRIPTION
**Pull request by ivoalmeida**
changed schema type for pvc-name from string to type PersistenVolumeClaimKind

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
/retitle changed schema type for pvc-name from string to type PersistenVolumeClaimKind

**Comment by SanjalKatiyar** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2158922

**Comment by SanjalKatiyar** [comment]
/retitle change schema type for pvc-name from string to type PersistenVolumeClaimKind

**Comment by SanjalKatiyar** [comment]
plz shorten the commit title a bit @ivoalmeida

**Comment by ivoalmeida** [comment]
> plz shorten the commit title a bit @ivoalmeida

@SanjalKatiyar how short?

**Comment by SanjalKatiyar** [comment]
> > plz shorten the commit title a bit @ivoalmeida
> 
> @SanjalKatiyar how short?

that is a good question, maybe we can add a workflow to check this moving ahead...
for now if u see https://github.com/red-hat-storage/odf-console/pull/850/commits u will see that title is kind of overflowing... so long enough that it won;t overflow...

**Comment by SanjalKatiyar** [comment]
> > > plz shorten the commit title a bit @ivoalmeida
> > 
> > 
> > @SanjalKatiyar how short?
> 
> that is a good question, maybe we can add a workflow to check this moving ahead... for now if u see https://github.com/red-hat-storage/odf-console/pull/850/commits u will see that title is kind of overflowing... so long enough that it won;t overflow...

cc @ivoalmeida PTAL.

**Comment by ivoalmeida** [comment]
> > > > plz shorten the commit title a bit @ivoalmeida
> > > 
> > > 
> > > @SanjalKatiyar how short?
> > 
> > 
> > that is a good question, maybe we can add a workflow to check this moving ahead... for now if u see https://github.com/red-hat-storage/odf-console/pull/850/commits u will see that title is kind of overflowing... so long enough that it won;t overflow...
> 
> cc @ivoalmeida PTAL.

done :)

**Comment by SanjalKatiyar** [comment]
@ivoalmeida can u rebase with latest master once ? CI is not passing !

**Pull request merged**
