### PR TITLE
Upgrading 'react-router-dom-v5-compat' package to 6.27.0

### PR DESCRIPTION
**Pull request by aruniiird**
Upgrading 'react-router-dom-v5-compat' package from '6.11.2' version to '6.27.0'
and
Removing the 'react-router-dom' package from dependencies

Task link: https://issues.redhat.com/browse/RHSTOR-6592

### CODE REVIEW

**Comment by aruniiird** [comment]
@alfonsomthd , @SanjalKatiyar , please take a look...

**Review by alfonsomthd — COMMENTED** [review]
LGTM. @SanjalKatiyar to tag it.

**Comment by SanjalKatiyar** [comment]
/lgtm cancel
@aruniiird plz squash the commits...

**Pull request merged**
