### PR TITLE
UI dev. deps: replace deprecated node-sass with dart-sass

### PR DESCRIPTION
**Pull request by alfonsomthd**
https://sass-lang.com/blog/libsass-is-deprecated

Fix: build with node >=15. Builds (yarn build / build-mco) tested with node 14/15/16.

GitHub action updated to include a build matrix for node 14 - 18.

Signed-off-by: Alfonso Martínez <almartin@redhat.com>

### CODE REVIEW

**Comment by bipuladh** [comment]
Can you specify 
` "engines" : { ` in package.json
Also could you create a `.nvmrc` file to ease users in automatically choosing the node version.

**Comment by alfonsomthd** [comment]
> Can you specify `"engines" : {` in package.json Also could you create a `.nvmrc` file to ease users in automatically choosing the node version.

Sure. Done!

**Review by bipuladh — APPROVED** [review]
/lgtm

**Pull request merged**
