### PR TITLE
migrate: css co classes to odf specific

### PR DESCRIPTION
**Pull request by debjyoti-pandit**
**Operand status master**
image

**Operand status current**
image

_______________________________________________________________________________________

**KMS Config master**
image
image

**KMS Config current**
image
image

_______________________________________________________________________________________

**Attach to deployment master**
image

**Attach to deployment current**
image

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
if tests are failing try re-basing with latest master...

**Comment by bipuladh** [comment]
/hold 
need to squash commits

**Pull request merged**
