### PR TITLE
Fix css issue with OBC claim details page

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
1. Fixed line space issue with a details page header.
2. Fixed copy-to-clip-board style issue.

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
image

**Comment by GowthamShanmugam** [comment]
image

**Comment by vbnrh** [comment]
Please update the description with the parts that have been fixed

**Pull request merged**
