### PR TITLE
Add the valid AWS GovCloud regions

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@bipuladh , @SanjalKatiyar Please review

**Comment by TimothyAsirJeyasing** [comment]
Screenshot from 2023-03-18 21-37-06
Screenshot from 2023-03-18 21-42-17

**Review by bipuladh — APPROVED** [review]
/lgtm

**Comment by SanjalKatiyar** [comment]
once backport PRs are up (after this master PR is merged), add the BZ number to the title of both PRs and make sure both PRs are added to "Links" section of the BZ... after that we can move BZ to "POST" and need to ask for "qa_ack" on the BZ... once done we can merge the backport PRs and move BZ to MODIFIED...

**Pull request merged**
