### PR TITLE
use generic names for Data Foundation

### PR DESCRIPTION
**Pull request by umangachapagain**
Updated names from "OpenShift Data Foundation" to "Data Foundation" to keep it generic.

### CODE REVIEW

**Review by bipuladh — CHANGES_REQUESTED** [review]
https://github.com/red-hat-storage/odf-console/pull/602/files#diff-bddf1b45c5882191e67bfc176d5c212e3d0ff6f5cc37e3992c82d6726fd185fbL40
Needs changes as well

**Review by bipuladh — APPROVED** [review]

**Review by GowthamShanmugam — APPROVED** [review]

**Pull request merged**
