### PR TITLE
Fix label overriding issue when same label is used with different values

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
It's a hack to fix the issue without any design change.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2210762

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
Screenshot 2024-08-30 at 5 02 37 PM

**Comment by GowthamShanmugam** [comment]
`pvcSelector:
    matchExpressions:
      - key: appname
        operator: In
        values:
          - busybox_app1
          - busybox
      - key: app-name
        operator: In
        values:
          - app-busybox-rbd-1`

**Review by bipuladh — APPROVED** [review]
/lgtm

**Pull request merged**
