### PR TITLE
Add tooltip for external object provider used capacity

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2246364

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
file:///home/timothyasir/Pictures/Screenshots/Screenshot%20from%202024-04-29%2015-01-29.png

**Review by bipuladh — APPROVED** [review]
/lgtm

**Comment by SanjalKatiyar** [comment]
@TimothyAsirJeyasing please backport the PRs and get acks on the BZ.

**Pull request merged**
