### PR TITLE
Bug 2310154: [release-4.15] Fix tar CVE issue

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
The PR is manually taken from https://github.com/red-hat-storage/odf-console/pull/1473

https://bugzilla.redhat.com/show_bug.cgi?id=2310154 
https://bugzilla.redhat.com/show_bug.cgi?id=2310153 
https://bugzilla.redhat.com/show_bug.cgi?id=2310140

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
The dist files are removed and noticed it gets copied during run time:-

Screenshot from 2024-09-09 18-14-40
image

**Comment by SanjalKatiyar** [comment]
u need to test whether translations are working with OCP 4.15 and locales are getting created as expected...

**Comment by TimothyAsirJeyasing** [comment]
image
image

**Review by bipuladh — APPROVED** [review]
/lgtm

**Pull request merged**
