### PR TITLE
Rephrase ODF minimum supported error message

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2087278
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
error_msg

**Comment by GowthamShanmugam** [comment]
Got approval from UX

**Review by SanjalKatiyar — APPROVED** [review]

**Pull request merged**
