### PR TITLE
Add object-service-dashboard test

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Screenshot from 2022-05-23 13-09-41

Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@bipuladh , @vbnrh Please review, This PR will go after obc-test

**Comment by bipuladh** [comment]
/test ci/prow/odf-console-e2e-aws
Checking for flakiness.

**Pull request merged**
