### PR TITLE
Bug 2185042: Change System capacity to System raw capacity

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
bz: https://bugzilla.redhat.com/show_bug.cgi?id=2185042

updated the system capacity to system raw capacity as per the suggestion given in the bz based on
second option provided in the bz at https://bugzilla.redhat.com/show_bug.cgi?id=2185042#c0
as heading shared in many places.

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
> image
> 
> @SanjalKatiyar , @GowthamShanmugam Please review

plz check the BZ again, this is not the original ask on the BZ...
also confirm with UX once before changing the text...

**Comment by SanjalKatiyar** [comment]
this BZ is for 4.14 only, add the BZ number to the title here...

**Comment by SanjalKatiyar** [comment]
also check the impact on the documentation...
we might have to update doc as well, if this name is used there...

**Comment by alfonsomthd** [comment]
@SanjalKatiyar In the BZ description it says: `Changing "Used Capacity" to "Used Raw Capacity", or alternatively the "System Capacity" card could be changed to "System Raw Capacity". Either would be more more explicit that the metric shown is raw utilization.` 
So I understand that `System Raw Capacity` is also accepted...

**Comment by SanjalKatiyar** [comment]
> @SanjalKatiyar In the BZ description it is said: `Changing "Used Capacity" to "Used Raw Capacity", or alternatively the "System Capacity" card could be changed to "System Raw Capacity". Either would be more more explicit that the metric shown is raw utilization.` So I understand that `System Raw Capacity` is also accepted...

yeah, my bad...
but changes are not discussed with UX and doc team yet...

**Comment by SanjalKatiyar** [comment]
for MCG (noobaa) standalone StorageSystem deployment, there is no "total"... will it make sense to add "raw" to the card name for such cases ??
cc @bipuladh

**Comment by TimothyAsirJeyasing** [comment]
Screenshot from 2023-05-09 15-42-10

**Comment by TimothyAsirJeyasing** [comment]
/retitle Bug 2185042: Change System capacity to System raw capacity

**Comment by SanjalKatiyar** [comment]
/hold
changes are not as per current UX mocks: https://www.figma.com/file/M5woHiyqSCWQwu5GTRoPwj/Fusion-ODF-monitoring?type=design&node-id=580-11656&t=E5d96xsEWD7d3Cly-0

**Comment by TimothyAsirJeyasing** [comment]
Screenshot from 2023-06-12 16-25-58

**Comment by SanjalKatiyar** [comment]
/close
needs more changes, this PR is not complete...

**Pull request closed without merging**
