### PR TITLE
Bug 2019654: url link for system systems

### PR DESCRIPTION
**Pull request by shdn-ibm**
fix https://bugzilla.redhat.com/show_bug.cgi?id=2019654

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
small FYI, as per https://bugzilla.redhat.com/show_bug.cgi?id=2005282, now, system-list page also points to the URL with systemName (just like dashboard) instead of pointing to storageCluster name.

**Comment by SanjalKatiyar** [comment]
/retitle Bug 2019654: url link for system systems

**Comment by afreen23** [comment]
Yes, with fix went in https://github.com/openshift/console/pull/10262
We dont want to do this anymore.
All routes will incorporate StorageSystem name

**Comment by shdn-ibm** [comment]
This fix is for the overview page. I think it is different from the list page.

**Pull request closed without merging**
