### PR TITLE
Bug 2239093: [release-4.14] Fix tooltips messages in the graphs at DR Policy dashboard

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
https://bugzilla.redhat.com/show_bug.cgi?id=2239093 https://bugzilla.redhat.com/show_bug.cgi?id=2239096 https://bugzilla.redhat.com/show_bug.cgi?id=2239101

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
/retitle Bug 2239093: [release-4.14] Fix tooltips messages in the graphs at DR Policy dashboard

**Comment by SanjalKatiyar** [comment]
> /approve

cc @GowthamShanmugam for LGTM

**Review by GowthamShanmugam — APPROVED** [review]

**Pull request merged**
