### PR TITLE
Bug 2290863: [release-4.15] Fix dashboard queries (Inventory + Capacity + Utilization cards)

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
https://github.com/red-hat-storage/odf-console/pull/1409

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
image

**Comment by SanjalKatiyar** [comment]
please test the PR... check the BZ and description of 4.16 PR for more details...

**Comment by alfonsomthd** [comment]
@TimothyAsirJeyasing Are the [conflicts](https://github.com/red-hat-storage/odf-console/pull/1409#issuecomment-2154672273) solved?

**Review by bipuladh — COMMENTED** [review]
@SanjalKatiyar ptal

**Comment by SanjalKatiyar** [comment]
LGTM

**Comment by SanjalKatiyar** [comment]
`packages/ocs/dashboards/persistent-external/client-fallback.ts` file is not deleted... but we can leave it for now...

**Pull request merged**
