### PR TITLE
Prevent the user from clicking the Optimize button multiple times

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2258996

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@SanjalKatiyar , @GowthamShanmugam Please review

**Comment by SanjalKatiyar** [comment]
what is the UX suggestion for this ??

**Comment by SanjalKatiyar** [comment]
> image

Alerts section and OSD migration status section are overlapping ?

**Comment by GowthamShanmugam** [comment]
> > image
> 
> Alerts section and OSD migration status section are overlapping ?

This PR is not required or we  may need to change this option to disable blue-store-RDR, Please check with @sp98

**Comment by TimothyAsirJeyasing** [comment]
The migration feature from bluestore to bluestore-rdr will be removed in the next release (4.17). Any such valid issues will be addressed along with the epic: https://issues.redhat.com/browse/RHSTOR-5722

**Pull request closed without merging**
