### PR TITLE
migrate(mco): css co classes to odf specific

### PR DESCRIPTION
**Pull request by debjyoti-pandit**
**Current **
image

**Master**
image

### CODE REVIEW

**Review by bipuladh — APPROVED** [review]
/lgtm

**Comment by SanjalKatiyar** [comment]
> Seems like the path for the `style.scss` here in the 3 files are incorrect and causing the build to fail.
> 
> ```
> ERROR in ./packages/mco/components/mco-dashboard/storage-system/dashboard.tsx 9:0-26
> Error: Can't resolve '../../style.scss' in '/remote-source/odf-console/app/packages/mco/components/mco-dashboard/storage-system'
> ```
> 
> ```
> ERROR in ./packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.tsx 18:0-32
> Error: Can't resolve '../../../../style.scss' in '/remote-source/odf-console/app/packages/mco/components/modals/drpolicy-apps-apply'
> ```

@debjyoti-pandit PTAL

**Comment by debjyoti-pandit** [comment]
> Seems like the path for the `style.scss` here in the 3 files are incorrect and causing the build to fail.
> 
> ```
> ERROR in ./packages/mco/components/mco-dashboard/storage-system/dashboard.tsx 9:0-26
> Error: Can't resolve '../../style.scss' in '/remote-source/odf-console/app/packages/mco/components/mco-dashboard/storage-system'
> ```
> 
> ```
> ERROR in ./packages/mco/components/modals/drpolicy-apps-apply/apply-policy-modal.tsx 18:0-32
> Error: Can't resolve '../../../../style.scss' in '/remote-source/odf-console/app/packages/mco/components/modals/drpolicy-apps-apply'
> ```

Where can I check/see the error It seems to be working (the build is passing in locally and also in the master branch stages)

image

**Comment by nik-redhat** [comment]
I don't think that we are building the mco component anywhere, that's the reason we are not seeing this issue on the master branch or PR's checks. Something to consider.
However, I can share with you the link on gchat.

**Comment by SanjalKatiyar** [comment]
> I don't think that we are building the mco component anywhere, that's the reason we are not seeing this issue on the master branch or PR's checks. Something to consider. However, I can share with you the link on gchat.

yes, we need to use "yarn build-mco" to check locally...
mco has a diff build and CI only test for ODF build right now...

**Comment by nik-redhat** [comment]
> yes, we need to use "yarn build-mco" to check locally as well as in CI... mco has a diff build and CI only test for ODF build right now...

I would suggest, we should be having a mco build on PRs at least. We can tweak the github action to run only when there are changes under the respective directory or a path, to avoid redundant builds. But, it will help to catch such issues early.

**Pull request merged**
