### PR TITLE
Bug 2275254: [release-4.16-compatibility] Count namespace protected DRPC as one application

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@GowthamShanmugam , @SanjalKatiyar Please review

**Comment by TimothyAsirJeyasing** [comment]
image

**Comment by GowthamShanmugam** [comment]
/retitle Bug 2275254: [release-4.16-compatibility] Count namespace protected DRPC as one application

**Review by GowthamShanmugam — APPROVED** [review]

**Pull request merged**
