### PR TITLE
Bug 2156069: Instances of OCS can be seen on BlockPool action modals

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Signed-off-by: Timothy Asir <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@SanjalKatiyar Please review

**Comment by TimothyAsirJeyasing** [comment]
Screenshot from 2023-01-04 15-43-01
Screenshot from 2023-01-04 15-42-50

**Comment by SanjalKatiyar** [comment]
/retitle Bug 2156069: Instances of OCS can be seen on BlockPool action modals

**Pull request merged**
