### PR TITLE
Fix lint warning: upgrade typescript-eslint

### PR DESCRIPTION
**Pull request by alfonsomthd**
https://github.com/openshift/release/pull/33719 needed for CI checks to pass.

Fix warning that appears on linting (introduced by https://github.com/red-hat-storage/odf-console/pull/512):
`WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.`

Signed-off-by: Alfonso Martínez <almartin@redhat.com>

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
adding label to test something, will remove the label in a while...

**Comment by SanjalKatiyar** [comment]
adding label to test something, will remove the label in a while...
/approve

**Comment by SanjalKatiyar** [comment]
> adding label to test something, will remove the label in a while... /approve

/approve cancel

**Review by SanjalKatiyar — APPROVED** [review]
testing...

**Comment by SanjalKatiyar** [comment]
testing...
/lgtm

**Comment by SanjalKatiyar** [comment]
> testing... /lgtm

/lgtm cancel

**Review by bipuladh — APPROVED** [review]
/lgtm

**Pull request merged**
