### PR TITLE
Add missing snapshot sync info for AppSet

### PR DESCRIPTION
**Pull request by SanjalKatiyar**
https://bugzilla.redhat.com/show_bug.cgi?id=2295324

### **Before:**
Screenshot 2024-07-03 at 12 00 01 PM

### **After:**
Screenshot 2024-07-03 at 12 00 26 PM

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
skipping e2e tests as they are only for ODF and this is MCO fix...

/override ci/prow/odf-console-e2e-aws

**Review by bipuladh — APPROVED** [review]
/lgtm

**Pull request merged**
