### PR TITLE
Fix Multiple instances of Object Bucket, Object Bucket Claims under storage section

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by bipuladh** [comment]
Let's fix Data Foundation to before PV.

**Comment by GowthamShanmugam** [comment]
image

**Comment by GowthamShanmugam** [comment]
> Let's fix Data Foundation to before PV.

Data Foundation is already has inserBefore pv check
https://github.com/red-hat-storage/odf-console/blob/886140ac6b8b3c4fe652f349f033d96dc4736b7a/console-extensions.json#L145

**Review by bipuladh — CHANGES_REQUESTED** [review]
Please fix order of data foundation nav item as well

**Pull request merged**
