### PR TITLE
Bug 2097772: [release-4.12] Show tooltips for contextual information

### PR DESCRIPTION
**Pull request by rexagod**
Show tooltips for contextual information while allowing users to override their behaviour.

Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
/retitle Bug 2097772: [release-4.12] Show tooltips for contextual information

**Comment by SanjalKatiyar** [comment]
/approve
@GowthamShanmugam plz lgtm if it looks good... u can change status of ur DR BZ as well once these PRs are merged...

**Review by GowthamShanmugam — APPROVED** [review]

**Pull request merged**
