### PR TITLE
Bug 2213552: Modified to a standard time format in DR pages

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2213552

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
/retitle Bug 2213552: Modified to a standard time format in DR pages

**Comment by SanjalKatiyar** [comment]
@GowthamShanmugam I have a doubt here (no need to make any changes in this PR)... but everywhere in ODF and now MCO while formatting time we are considering it as UTC timezone, is that alright to always convert to UTC... cluster can be in other timezones as well...

**Comment by GowthamShanmugam** [comment]
> @GowthamShanmugam I have a doubt here (no need to make any changes in this PR)... but everywhere in ODF and now MCO while formatting time we are considering it as UTC timezone, is it all alright to always convert to UTC... cluster can be in other timezones as well... need to check how OCP does it...

Yes, clusters can be deployed in different zones, To resolve this time format issue, OCP is following UTC as a common time zone. Everywhere on the list page, they are using local time to display but popover  UTC is used as a common timezone.

**Comment by SanjalKatiyar** [comment]
> > @GowthamShanmugam I have a doubt here (no need to make any changes in this PR)... but everywhere in ODF and now MCO while formatting time we are considering it as UTC timezone, is it all alright to always convert to UTC... cluster can be in other timezones as well... need to check how OCP does it...
> 
> Yes, clusters can be deployed in different zones, To resolve this time format issue, OCP is following UTC as a common time zone. Everywhere on the list page, they are using local time to display but popover UTC is used as a common timezone.

so if OCP is using local time for page, it means we are doing it wrong in ODF ?? I think in ODF we always use UTC (for list as well as popover) right ??

**Comment by GowthamShanmugam** [comment]
> > > @GowthamShanmugam I have a doubt here (no need to make any changes in this PR)... but everywhere in ODF and now MCO while formatting time we are considering it as UTC timezone, is it all alright to always convert to UTC... cluster can be in other timezones as well... need to check how OCP does it...
> > 
> > 
> > Yes, clusters can be deployed in different zones, To resolve this time format issue, OCP is following UTC as a common time zone. Everywhere on the list page, they are using local time to display but popover UTC is used as a common timezone.
> 
> so if OCP is using local time for the list page, it means we are doing it wrong in ODF ?? I think in ODF we always use UTC (for list as well as popover) right ??

OCP is using UTC + local time. LocalTime to display text and UTC as a tooltip popover text. I think the place we can't provide popover its is correct to use UTC.

**Comment by SanjalKatiyar** [comment]
> OCP is using UTC + local time. LocalTime to display text and UTC as a tooltip popover text. I think the place we can't provide popover its is correct to use UTC.

I meant in ODF/MCO list pages as well we are using UTC instead of local time... anyway that's not related to this PR...

**Pull request merged**
