### PR TITLE
Bug 2255332: [release-4.15] DR UI textual update

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
This PR is a manual merge from [1157](https://github.com/red-hat-storage/odf-console/pull/1157)

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
Screenshot from 2024-01-22 13-58-56
Screenshot from 2024-01-22 14-00-13
Screenshot from 2024-01-22 13-57-58

**Comment by TimothyAsirJeyasing** [comment]
@SanjalKatiyar , @GowthamShanmugam Please review

**Review by GowthamShanmugam — APPROVED** [review]

**Pull request merged**
