### PR TITLE
Fix webhook warning in bucket and obc creation

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
https://issues.redhat.com/browse/DFBUGS-389
bz: https://bugzilla.redhat.com/show_bug.cgi?id=2311546

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
Screenshot from 2024-11-12 13-06-49

**Comment by TimothyAsirJeyasing** [comment]
After:
Screenshot from 2024-11-15 11-43-31
Screenshot from 2024-11-15 11-42-46
Screenshot from 2024-11-15 11-42-15

**Comment by alfonsomthd** [comment]
LGTM. @SanjalKatiyar @bipuladh to add `approve` tag.

**Pull request merged**
