### PR TITLE
Update react router dom

### PR DESCRIPTION
**Pull request by SanjalKatiyar**
https://www.npmjs.com/package/react-router-dom-v5-compat

**Introduce react-router v6 compatibility:**

- Bumps "react-router", "react-router-dom", their respective types and "dynamic-plugin-sdk-webpack".
- Adds "react-router-dom-v5-compat".

**React router migration:**

- Migrates from "react-router" and "react-router-dom" to "react-router-dom-v5-compat".

**Fix horizontal navigation:**

- Moves usage of "HorizontalNav" from sdk to "Tabs" from shared (for "Object Storage" nav item).
- Updated unit/e2e tests.

### CODE REVIEW

**Review by GowthamShanmugam — COMMENTED** [review]
LGTM

**Review by bipuladh — APPROVED** [review]
/lgtm

**Pull request merged**
